# Generated by Django 2.2.1 on 2019-06-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190629_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address_next',
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
