# Generated by Django 2.2.1 on 2019-06-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190630_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
    ]
